<?php
/**
 * One-shot web installer for Devithor LMS backend.
 *
 *  Visit https://your-domain/install.php after uploading the repo. The wizard
 *  walks you through:
 *    1. Server requirements check
 *    2. Database credentials → writes .env
 *    3. Schema migrations
 *    4. First admin user
 *    5. Lock-down — install.php refuses to run again until you delete the
 *       `.installed` flag file.
 *
 *  IMPORTANT: After step 5, **delete this file** from the server. Even with
 *  the lock in place, leaving a public installer endpoint is bad hygiene.
 */

declare(strict_types=1);

ini_set('display_errors', '1');
error_reporting(E_ALL);

$projectRoot    = dirname(__DIR__);
$envPath        = $projectRoot . '/.env';
$lockPath       = $projectRoot . '/.installed';
$migrationsDir  = $projectRoot . '/migrations';

$step = $_GET['step'] ?? 'welcome';

// ---- Lock-out: refuse to do anything once installed --------------------
if (file_exists($lockPath) && $step !== 'locked') {
    header('Location: install.php?step=locked');
    exit;
}

// ---- Action handlers ----------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';
    try {
        if ($action === 'save_env') {
            handleSaveEnv($envPath);
            redirect('install.php?step=migrate');
        }
        if ($action === 'migrate') {
            $applied = runMigrations($envPath, $migrationsDir);
            renderPage('Migrations', migrateSuccessHtml($applied));
            exit;
        }
        if ($action === 'create_admin') {
            handleCreateAdmin($envPath, $lockPath);
            redirect('install.php?step=done');
        }
    } catch (Throwable $e) {
        renderPage('Error', errorHtml($e->getMessage()));
        exit;
    }
}

// ---- Page router --------------------------------------------------------
switch ($step) {
    case 'requirements': renderPage('Requirements', requirementsHtml()); break;
    case 'db':           renderPage('Database',     dbFormHtml($envPath)); break;
    case 'migrate':      renderPage('Migrations',   migratePromptHtml()); break;
    case 'admin':        renderPage('Admin user',   adminFormHtml()); break;
    case 'done':         renderPage('Done',         doneHtml()); break;
    case 'locked':       renderPage('Already installed', lockedHtml($lockPath)); break;
    default:             renderPage('Welcome',      welcomeHtml());
}
exit;

// =======================================================================
//  ACTION HANDLERS
// =======================================================================

function handleSaveEnv(string $envPath): void
{
    $needed = ['DB_HOST', 'DB_PORT', 'DB_DATABASE', 'DB_USERNAME', 'DB_PASSWORD', 'APP_URL'];
    $vals = [];
    foreach ($needed as $k) {
        $v = trim((string) ($_POST[$k] ?? ''));
        if ($v === '' && $k !== 'DB_PASSWORD') {
            throw new RuntimeException("Field $k is required.");
        }
        $vals[$k] = $v;
    }

    // Sanity-check the connection BEFORE writing .env so we don't lock the
    // user into a bad config that needs SSH to fix.
    try {
        $dsn = "mysql:host={$vals['DB_HOST']};port={$vals['DB_PORT']};dbname={$vals['DB_DATABASE']};charset=utf8mb4";
        new PDO($dsn, $vals['DB_USERNAME'], $vals['DB_PASSWORD'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
    } catch (PDOException $e) {
        throw new RuntimeException('Could not connect to the database with those credentials. Double-check host, name, user, and password in hPanel. (' . $e->getMessage() . ')');
    }

    // Auto-generate APP_KEY so the user never has to think about it.
    $appKey  = base64_encode(random_bytes(48));
    $stamp   = date('c');
    $appName = 'Devithor LMS';

    $env = <<<ENV
# Generated by install.php on $stamp
APP_NAME="$appName"
APP_ENV=production
APP_DEBUG=false
APP_URL={$vals['APP_URL']}
APP_TIMEZONE=UTC
APP_KEY=$appKey

DB_HOST={$vals['DB_HOST']}
DB_PORT={$vals['DB_PORT']}
DB_DATABASE={$vals['DB_DATABASE']}
DB_USERNAME={$vals['DB_USERNAME']}
DB_PASSWORD={$vals['DB_PASSWORD']}
DB_CHARSET=utf8mb4

CORS_ALLOWED_ORIGINS=
LOG_LEVEL=info
ENV;

    if (file_put_contents($envPath, $env) === false) {
        throw new RuntimeException("Couldn't write .env to $envPath. The web server user needs write permission on the project root.");
    }
    @chmod($envPath, 0600);
}

function runMigrations(string $envPath, string $migrationsDir): array
{
    if (!is_file($envPath)) {
        throw new RuntimeException('.env not found. Go back to step 2.');
    }

    $env = parseEnv($envPath);
    $pdo = pdoFrom($env);

    $pdo->exec(
        'CREATE TABLE IF NOT EXISTS schema_migrations (
            filename VARCHAR(255) PRIMARY KEY,
            applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'
    );

    $applied = [];
    $stmt = $pdo->query('SELECT filename FROM schema_migrations');
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $applied[$row['filename']] = true;
    }

    $files = glob($migrationsDir . '/*.sql') ?: [];
    sort($files);
    $newlyApplied = [];

    foreach ($files as $file) {
        $name = basename($file);
        if (isset($applied[$name])) continue;
        $sql = (string) file_get_contents($file);
        if (trim($sql) === '') continue;
        foreach (preg_split('/;\s*$/m', $sql) as $stmt) {
            $stmt = trim($stmt);
            if ($stmt === '') continue;
            $pdo->exec($stmt);
        }
        $insert = $pdo->prepare('INSERT INTO schema_migrations (filename) VALUES (?)');
        $insert->execute([$name]);
        $newlyApplied[] = $name;
    }

    return $newlyApplied;
}

function handleCreateAdmin(string $envPath, string $lockPath): void
{
    $email    = strtolower(trim((string) ($_POST['email'] ?? '')));
    $name     = trim((string) ($_POST['full_name'] ?? ''));
    $password = (string) ($_POST['password'] ?? '');
    $confirm  = (string) ($_POST['password_confirm'] ?? '');

    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) throw new RuntimeException('Enter a valid email.');
    if (mb_strlen($name) < 2)                       throw new RuntimeException('Name is too short.');
    if (mb_strlen($password) < 12)                  throw new RuntimeException('Password must be at least 12 characters.');
    if ($password !== $confirm)                     throw new RuntimeException("Passwords don't match.");

    $env = parseEnv($envPath);
    $pdo = pdoFrom($env);

    $existing = $pdo->prepare('SELECT id FROM users WHERE email = ?');
    $existing->execute([$email]);
    $row = $existing->fetch(PDO::FETCH_ASSOC);

    $hash = password_hash($password, PASSWORD_DEFAULT);
    if ($row) {
        // Promote the existing user to admin and reset password.
        $up = $pdo->prepare('UPDATE users SET role = ?, password_hash = ?, full_name = ? WHERE id = ?');
        $up->execute(['ADMIN', $hash, $name, $row['id']]);
    } else {
        $id = 'u_' . bin2hex(random_bytes(8));
        $ins = $pdo->prepare('INSERT INTO users (id, email, full_name, role, password_hash) VALUES (?, ?, ?, ?, ?)');
        $ins->execute([$id, $email, $name, 'ADMIN', $hash]);
    }

    // Lock the installer so it can't run again.
    file_put_contents($lockPath, "Installed at " . date('c') . "\nDelete this file (and install.php) only if you really want to re-run the installer.\n");
    @chmod($lockPath, 0600);
}

// =======================================================================
//  HELPERS
// =======================================================================

function parseEnv(string $path): array
{
    $out = [];
    foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) continue;
        [$k, $v] = explode('=', $line, 2);
        $k = trim($k); $v = trim($v);
        if (strlen($v) >= 2 && ($v[0] === '"' || $v[0] === "'")) $v = substr($v, 1, -1);
        $out[$k] = $v;
    }
    return $out;
}

function pdoFrom(array $env): PDO
{
    $dsn = "mysql:host={$env['DB_HOST']};port={$env['DB_PORT']};dbname={$env['DB_DATABASE']};charset=utf8mb4";
    return new PDO($dsn, $env['DB_USERNAME'], $env['DB_PASSWORD'], [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
    ]);
}

function redirect(string $to): never
{
    header("Location: $to");
    exit;
}

function e(?string $v): string
{
    return htmlspecialchars((string) $v, ENT_QUOTES | ENT_HTML5, 'UTF-8');
}

// =======================================================================
//  HTML — self-contained, no /assets dependency
// =======================================================================

function renderPage(string $title, string $body): void
{
    $css = '
        :root { --bg:#0B0F1A; --surface:#131830; --border:#2A3050; --text:#E6E9F2; --muted:#9AA3BE; --primary:#7C5CFF; --primary-hover:#6647FF; --success:#10B981; --danger:#EF4444; }
        * { box-sizing:border-box; }
        body { margin:0; padding:40px 20px; background:var(--bg); color:var(--text); font:14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; min-height:100vh; }
        .wrap { max-width:560px; margin:0 auto; }
        .brand { color:var(--primary); font-weight:800; font-size:20px; margin-bottom:6px; letter-spacing:-0.5px; }
        .step { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.6px; margin-bottom:24px; }
        .card { background:var(--surface); border:1px solid var(--border); border-radius:14px; padding:28px; margin-bottom:18px; }
        h1 { margin:0 0 8px; font-size:22px; font-weight:700; }
        h2 { margin:24px 0 8px; font-size:16px; }
        p  { margin:0 0 14px; color:var(--text); }
        .muted { color:var(--muted); }
        ul { margin:0 0 14px; padding-left:18px; } li { margin-bottom:6px; }
        label { display:block; font-size:13px; font-weight:600; color:var(--muted); margin:14px 0 6px; }
        input[type=text],input[type=email],input[type=password],input[type=url] { width:100%; background:var(--bg); border:1px solid var(--border); border-radius:8px; padding:10px 12px; color:var(--text); font-size:14px; font-family:inherit; }
        input:focus { outline:none; border-color:var(--primary); box-shadow:0 0 0 3px rgba(124,92,255,.18); }
        .row { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
        .btn { display:inline-block; padding:11px 20px; border:none; border-radius:10px; font-size:14px; font-weight:600; cursor:pointer; text-decoration:none; }
        .btn-primary { background:var(--primary); color:#fff; }
        .btn-primary:hover { background:var(--primary-hover); }
        .btn-secondary { background:transparent; color:var(--muted); border:1px solid var(--border); }
        .alert { padding:12px 14px; border-radius:10px; margin:0 0 16px; font-size:14px; }
        .alert-ok { background:rgba(16,185,129,.12); color:var(--success); }
        .alert-err { background:rgba(239,68,68,.12); color:var(--danger); }
        .alert-warn { background:rgba(245,158,11,.12); color:#F59E0B; }
        code { background:#000; padding:2px 6px; border-radius:4px; font-size:12px; }
        .check { color:var(--success); font-weight:700; }
        .cross { color:var(--danger); font-weight:700; }
    ';
    echo '<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex"><title>' . e($title) . ' · Devithor installer</title><style>' . $css . '</style></head><body><div class="wrap"><div class="brand">Devithor LMS</div><div class="step">Installer</div>' . $body . '</div></body></html>';
}

function welcomeHtml(): string
{
    return '
        <div class="card">
            <h1>Welcome 👋</h1>
            <p>This wizard will set up your Devithor LMS backend on this server. It takes about 90 seconds.</p>
            <p class="muted">You\'ll need: your Hostinger MySQL credentials (database name, username, password) and an email + password for the first admin login.</p>
            <a href="install.php?step=requirements" class="btn btn-primary">Start →</a>
        </div>
        <p class="muted" style="text-align:center; font-size:12px">After install, delete <code>install.php</code> from the server.</p>';
}

function requirementsHtml(): string
{
    $checks = [
        ['PHP 8.2 or newer',          version_compare(PHP_VERSION, '8.2.0', '>='), PHP_VERSION],
        ['PDO MySQL extension',       extension_loaded('pdo_mysql'),               extension_loaded('pdo_mysql') ? 'loaded' : 'missing'],
        ['JSON extension',            extension_loaded('json'),                    extension_loaded('json') ? 'loaded' : 'missing'],
        ['mbstring extension',        extension_loaded('mbstring'),                extension_loaded('mbstring') ? 'loaded' : 'missing'],
        ['random_bytes available',    function_exists('random_bytes'),             function_exists('random_bytes') ? 'yes' : 'no'],
        ['Project root writable',     is_writable(dirname(__DIR__)),               is_writable(dirname(__DIR__)) ? 'yes' : 'no — chmod 755 on the project folder'],
    ];

    $rows = '';
    $allOk = true;
    foreach ($checks as [$label, $ok, $detail]) {
        if (!$ok) $allOk = false;
        $mark = $ok ? '<span class="check">✓</span>' : '<span class="cross">✗</span>';
        $rows .= "<li>$mark " . e($label) . " <span class=\"muted\">— " . e((string) $detail) . "</span></li>";
    }

    $cta = $allOk
        ? '<a href="install.php?step=db" class="btn btn-primary">Continue →</a>'
        : '<div class="alert alert-err">Fix the failed checks above before continuing. PHP version is the most common one — set it in hPanel → Websites → PHP Configuration.</div>';

    return "
        <div class=\"card\">
            <h1>Requirements check</h1>
            <ul>$rows</ul>
            $cta
        </div>";
}

function dbFormHtml(string $envPath): string
{
    // Pre-fill from any existing .env so a re-run doesn't make the user retype.
    $existing = is_file($envPath) ? parseEnv($envPath) : [];
    $host  = e($existing['DB_HOST']     ?? 'localhost');
    $port  = e($existing['DB_PORT']     ?? '3306');
    $name  = e($existing['DB_DATABASE'] ?? '');
    $user  = e($existing['DB_USERNAME'] ?? '');
    $url   = e($existing['APP_URL']     ?? 'https://' . ($_SERVER['HTTP_HOST'] ?? ''));

    return "
        <div class=\"card\">
            <h1>Database</h1>
            <p class=\"muted\">Paste the credentials for the MySQL database you created in hPanel → Databases → Management.</p>
            <form method=\"post\" action=\"install.php?step=db\">
                <input type=\"hidden\" name=\"action\" value=\"save_env\">

                <label>Public URL (where this app will live)</label>
                <input type=\"url\" name=\"APP_URL\" value=\"$url\" required>

                <div class=\"row\">
                    <div>
                        <label>Database host</label>
                        <input type=\"text\" name=\"DB_HOST\" value=\"$host\" required>
                    </div>
                    <div>
                        <label>Port</label>
                        <input type=\"text\" name=\"DB_PORT\" value=\"$port\" required>
                    </div>
                </div>

                <label>Database name</label>
                <input type=\"text\" name=\"DB_DATABASE\" value=\"$name\" placeholder=\"u123456789_appbackend\" required>

                <label>Database user</label>
                <input type=\"text\" name=\"DB_USERNAME\" value=\"$user\" placeholder=\"u123456789_appbackend\" required>

                <label>Database password</label>
                <input type=\"password\" name=\"DB_PASSWORD\" required autocomplete=\"new-password\">

                <div style=\"margin-top:20px\">
                    <button type=\"submit\" class=\"btn btn-primary\">Test &amp; save →</button>
                </div>
            </form>
        </div>";
}

function migratePromptHtml(): string
{
    return '
        <div class="card">
            <h1>Run migrations</h1>
            <p>Database connection works. Click below to create all tables (users, courses, lessons, billing, Q&A, bookmarks).</p>
            <p class="muted">Safe to re-run — only new migrations are applied.</p>
            <form method="post" action="install.php?step=migrate">
                <input type="hidden" name="action" value="migrate">
                <button type="submit" class="btn btn-primary">Apply migrations →</button>
            </form>
        </div>';
}

function migrateSuccessHtml(array $applied): string
{
    if (empty($applied)) {
        $list = '<p class="muted">No new migrations to apply — schema was already up to date.</p>';
    } else {
        $items = implode('', array_map(fn ($f) => '<li><code>' . e($f) . '</code></li>', $applied));
        $list  = '<p>Applied:</p><ul>' . $items . '</ul>';
    }
    return "
        <div class=\"alert alert-ok\">Migrations finished.</div>
        <div class=\"card\">
            $list
            <a href=\"install.php?step=admin\" class=\"btn btn-primary\">Continue →</a>
        </div>";
}

function adminFormHtml(): string
{
    return '
        <div class="card">
            <h1>First admin user</h1>
            <p class="muted">This account can sign in at <code>/admin/login</code> to manage courses and lessons.</p>
            <form method="post" action="install.php?step=admin">
                <input type="hidden" name="action" value="create_admin">

                <label>Full name</label>
                <input type="text" name="full_name" required>

                <label>Email</label>
                <input type="email" name="email" required>

                <label>Password (min 12 characters)</label>
                <input type="password" name="password" required minlength="12" autocomplete="new-password">

                <label>Confirm password</label>
                <input type="password" name="password_confirm" required minlength="12" autocomplete="new-password">

                <div style="margin-top:20px">
                    <button type="submit" class="btn btn-primary">Create admin →</button>
                </div>
            </form>
        </div>';
}

function doneHtml(): string
{
    $adminUrl = '/admin/login';
    return "
        <div class=\"alert alert-ok\">🎉 Install complete.</div>
        <div class=\"card\">
            <h1>You're all set</h1>
            <p>Sign in to your dashboard:</p>
            <p><a href=\"$adminUrl\" class=\"btn btn-primary\">Open /admin/login →</a></p>

            <h2>One last thing — clean up</h2>
            <ul>
                <li><strong>Delete <code>install.php</code></strong> from the server (via SSH or Hostinger File Manager). The lock file stops re-runs, but a deleted file is even better.</li>
                <li>Confirm <code>.env</code> is mode <code>600</code> (only your user can read it). Run <code>chmod 600 .env</code> over SSH if needed.</li>
                <li>Verify the API is live: <code>curl https://" . e($_SERVER['HTTP_HOST'] ?? '') . "/api/v1/health</code> should return <code>{\"status\":\"ok\"}</code>.</li>
            </ul>
        </div>";
}

function lockedHtml(string $lockPath): string
{
    return "
        <div class=\"alert alert-warn\">Already installed — installer disabled.</div>
        <div class=\"card\">
            <h1>This site is already set up</h1>
            <p>The lock file <code>" . e($lockPath) . "</code> exists, so the installer will refuse to run.</p>
            <p>If you genuinely need to re-install (say, you nuked the database), SSH in and remove both:</p>
            <ul>
                <li><code>" . e($lockPath) . "</code></li>
                <li><code>.env</code> (so the wizard re-prompts for credentials)</li>
            </ul>
            <p>Then visit this page again. <strong>Better still:</strong> just delete <code>install.php</code> entirely — you don't need it after first install.</p>
        </div>";
}

function errorHtml(string $message): string
{
    return '
        <div class="alert alert-err">' . e($message) . '</div>
        <div class="card">
            <p>Go back and try again:</p>
            <a href="javascript:history.back()" class="btn btn-secondary">← Back</a>
        </div>';
}
